In [1]:
import pandas as pd

In [15]:
df = pd.read_csv('data/Stackoverflow/survey_results_public.csv', index_col = 'Respondent')
df_schema = pd.read_csv('data/Stackoverflow/survey_results_schema.csv', index_col = 'Column')

pd.set_option('display.max_rows',85)
pd.set_option('display.max_columns',85)

#### Replace a colm or assign a new colname

In [ ]:
#df.columns = df.columns.str.replace(param,param)
#df.rename(columns = {'column': 'newname', 'column':newname}, inplace=True )

#### Convert to uppercase or lowercase

In [ ]:
#df['col'] = df['col'].str.lower()

#### Assign new row value to a col

In [ ]:
#filt = (df['col']) == 'value')
#df.loc[filt, 'colname'] = 'newname'

#### Functions
.apply() </br>
.applymap() - use when applying it to the whole df</br>
.map() - Substitituing a value

In [12]:
df.columns = [x.lower() for x in df.columns]
df.head()

,respondent,mainbranch,hobbyist,opensourcer,opensource,employment,country,student,edlevel,undergradmajor,...,welcomechange,sonewcontent,age,gender,trans,sexuality,ethnicity,dependents,surveylength,surveyease
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [21]:
df.rename(columns={'ConvertedComp':'SalaryUSD'}, inplace=True)

In [24]:
df['SalaryUSD']

Respondent
1            NaN
2            NaN
3         8820.0
4        61000.0
5            NaN
          ...
88377        NaN
88601        NaN
88802        NaN
88816        NaN
88863        NaN
Name: SalaryUSD, Length: 88883, dtype: float64